name: Build Container with Personal Top 10 List
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build Container
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: yourusername/top10:latest
        file: ./Dockerfile
      
    - name: Push Container to GitHub Package Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push to GitHub Package Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: docker.pkg.github.com/yourusername/top10:latest
