name: Run github workflow Scenario

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      
   
    - uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    
    - name: Build Container
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: shindeds/webserver:latest 
      env:
        TOP_10_FILE: ./top_10_list.html
    - name: Publish Container
      uses: docker/metadata-action@v3
      with:
        images: shindeds/webserver:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
       
  load_test:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        runner: [ubuntu-lates]
    steps:
    - uses: actions/checkout@v2
    - name: Run Sysbench
      run: |
        sudo apt-get update
        sudo apt-get install -y sysbench
        sysbench cpu --threads=2 --time=60 run     
        
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check for new version
        run: |
          docker pull nginx:latest
          if [[ "$(docker images -q nginx:latest 2> /dev/null)" != "" ]]; then
            echo "New version of nginx container available"
            # BONUS: commit, push and create a pull request for the new tag
          else
            echo "No new version of nginx container available"
          fi      
        
