name: Check for Container Upgrade

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check_upgrade:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Get Current Container Image Digest
      id: get_current_digest
      run: |
        echo "::set-output name=digest::$(docker inspect username/webserver:latest --format='{{json .Id}}')"
    - name: Get Latest Container Image Digest
      id: get_latest_digest
      run: |
        docker pull username/webserver:latest
        echo "::set-output name=digest::$(docker inspect username/webserver:latest --format='{{json .Id}}')"
    - name: Compare Digests
      id: compare_digests
      run: |
        echo "Current Digest: ${{ steps.get_current_digest.outputs.digest }}"
        echo "Latest Digest: ${{ steps.get_latest_digest.outputs.digest }}"
        if [[ "${{ steps.get_current_digest.outputs.digest }}" != "${{ steps.get_latest_digest.outputs.digest }}" ]]; then
          echo "New container version detected."
          echo "::set-output name=upgrade_available::true"
        else
          echo "No container upgrade available."
          echo "::set-output name=upgrade_available::false"
        fi
    - name: Create Pull Request
      if: steps.compare_digests.outputs.upgrade_available == 'true'
      uses: peter-evans/create-pull-request@
