
name: Check for Newer Version of Webserver Container
on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Check for newer version
      run: |
        current=$(docker image ls my-webserver --format '{{.Tag}}')
        latest=$(curl -s https://registry.hub.docker.com/v1/repositories/library/nginx/tags | jq -r '."name" | select(. != null)' | sort -rV
