name: Check for new version of nginx container

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check for new version
        run: |
          docker pull nginx:latest
          if [[ "$(docker images -q nginx:latest 2> /dev/null)" != "" ]]; then
            echo "New version of nginx container available"
            # BONUS: commit, push and create a pull request for the new tag
          else
            echo "No new version of nginx container available"
          fi
