
 

name: Build Webserver Container with Top 10 List
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-webserver .

    - name: Push Docker image
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      run: docker push my-webserver

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Pull Docker image
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      run: docker pull my-webserver

    - name: Start container
      run: docker run --name my-webserver-container -d -p 8080:80 -v "$(pwd)/top10.html:/usr/share/nginx/html/top10.html:ro" my-webserver
