name: Sysbench Load Test

on:
  workflow_dispatch:

jobs:
  load_test:
    runs-on: [ubuntu-latest, macos-latest]
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Run Sysbench
      run: |
        sudo apt-get update
        sudo apt-get install -y sysbench
        sysbench cpu --threads=2 --time=60 run
